url:        https://www.davekurman.com'
baseurl:    /
name:       Dave Kurman
description: >
  Dave Kurman / Computer Systems Analyst / Expertise in
  computer programming, database, web
  development, system administration

# Build settings
markdown:             kramdown
highlighter:          rouge

kramdown:
  line_width:         72
  input:              GFM
  fenced_code_blocks: true
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    default_lang: bash
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    # span:
    #   line_numbers: false
    # block:
    #   line_numbers: false
    #   wrap: false

# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Permalinks
permalink:            pretty

paginate:             5
paginate_path:        "/page:num/"
version:              1.3

